### ISSUE TITLE
Which identifiers to authenticate with?

### ISSUE THREAD

**Issue by johnweldon** [tempusbreve/authsvc#1]
Which LDAP attributes should be used to identify the user to be authenticated?

Default candidates from `inetOrgPerson`:
 - [x] `uid` (user id : like `jweldon`)
 - [ ] `dn` (distinguished name : like `cn=John Weldon,dc=breve,dc=us`)
 - [x] `mail` (email address : like `jweldon@breve.us`)

**Comment by johnweldon** [comment]
@tareko let me know if you have a strong opinion, on this - otherwise, I'll just go with all three.

**Comment by tareko** [comment]
Our use case is uid, but in other implementations I see this as configurable.

**Comment by johnweldon** [comment]
Defaulting to `uid` and `mail` for now.
